name: Build and pack win-x64

on:
  push:
    branches: [ "tmds_ssh_dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: dnf install -y mingw64-openssl cpio xz cmake mingw64-gcc-c++ binutils dotnet-sdk-6.0
    - name: Build libssh
      run: |
        mkdir build
        cd build
        mingw64-cmake ..
        make -j$(nproc)
        make install
        ls -lah /usr/x86_64-w64-mingw32/sys-root/mingw/bin
    - name: Create Nupkg
      run: |
        VERSION_SUFFIX="${{ github.run_number }}-${{ github.sha }}"
        dotnet pack -c Release nupkg --output . /p:TargetRid=win-x64 /p:VersionSuffix="$VERSION_SUFFIX"
    - name: Publish package
      run: |
        dotnet nuget push -s https://www.myget.org/F/tmds/api/v2/package -k "${{ secrets.NUGET_APIKEY }}" *.nupkg
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/tmds_ssh_dev' }}